name: IP Blacklist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Fetch
      run: |
        curl -G "https://api.abuseipdb.com/api/v2/blacklist" -d confidenceMinimum=85 -d limit=9999999 -d plaintext -H "Key: ${{ secrets.ABUSEIPDB_TOKEN }}" -H "Accept: text/plain" > lists/abuseipdb_blacklist_ip_score_85.txt || true
        curl "http://antivirus.neu.edu.cn/sshlists/neu.txt" -H "Accept: text/plain" > lists/neucert_blacklist_ip.txt || true
        curl "https://blackip.ustc.edu.cn/list.php?txt" -H "Accept: text/plain" > lists/ustc_blacklist_ip.txt || true
        curl "https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1" -H "Accept: text/plain" > lists/projecthoneypot_blacklist_ip.txt || true
        curl "https://check.torproject.org/torbulkexitlist?ip=1.1.1.1" -H "Accept: text/plain" > lists/torproject_blacklist_ip.txt || true
        curl "https://www.maxmind.com/en/high-risk-ip-sample-list" -H "Accept: text/plain" > lists/maxmind_blacklist_ip.txt || true
        curl "http://danger.rulez.sk/projects/bruteforceblocker/blist.php" -H "Accept: text/plain" > lists/bruteforceblocker_blacklist_ip.txt || true
        curl "https://www.spamhaus.org/drop/drop.lasso" -H "Accept: text/plain" > lists/spamhaus_blacklist_ip.txt || true
        curl "http://cinsscore.com/list/ci-badguys.txt" -H "Accept: text/plain" > lists/ci-badguys_blacklist_ip.txt || true
        curl "https://lists.blocklist.delists/all.txt" -H "Accept: text/plain" > lists/blocklistde_blacklist_ip.txt || true
        curl "http://blocklist.greensnow.co/greensnow.txt" -H "Accept: text/plain" > lists/greensnow_blacklist_ip.txt || true
        curl "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset" -H "Accept: text/plain" > lists/firehol_level1_blacklist_ip.txt || true
        curl "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_7d.ipset" -H "Accept: text/plain" > lists/stopforumspam_7d_blacklist_ip.txt || true
        curl "https://rules.emergingthreats.net/blockrules/compromised-ips.txt" -H "Accept: text/plain" > lists/emergingthreats_compromised_ips_blacklist_ip.txt || true
        curl "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt" -H "Accept: text/plain" > lists/emergingthreats_emerging_Block_IPs_blocklist_ip.txt || true
        for F in `ls *.txt`;do echo "">> $F; done
        cat lists/*.txt|grep -Po "(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?"|sort|uniq > combined_blacklists.txt
    - name: Commit
      run: |
        git config --global user.email action@github.com
        git config --global user.name Action
        git add .
        git commit -m "Update IPs." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
